/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overridden.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as DashboardIndexImport } from './pages/dashboard/index'
import { Route as LoginIndexImport } from './pages/login/index'
import { Route as ProductsAnalyzeIndexImport } from './pages/products/analyze/index'
import { Route as OnboardingIndexImport } from './pages/onboarding/index'
import { Route as PricingIndexImport } from './pages/pricing/index'
import { Route as SettingsIndexImport } from './pages/settings/index'
import { Route as SettingsBillingIndexImport } from './pages/settings/billing/index'
import { Route as SettingsProfileIndexImport } from './pages/settings/profile/index'
import { Route as StudioCreateIndexImport } from './pages/studio/create/index'
import { Route as StudioResultJobIdImport } from './pages/studio/result/$jobId'

// Create/Update Routes

const DashboardIndexRoute = DashboardIndexImport.update({
	id: '/dashboard/',
	path: '/dashboard/',
	getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
	id: '/login/',
	path: '/login/',
	getParentRoute: () => rootRoute,
} as any)

const ProductsAnalyzeIndexRoute = ProductsAnalyzeIndexImport.update({
	id: '/products/analyze/',
	path: '/products/analyze/',
	getParentRoute: () => rootRoute,
} as any)

const OnboardingIndexRoute = OnboardingIndexImport.update({
	id: '/onboarding/',
	path: '/onboarding/',
	getParentRoute: () => rootRoute,
} as any)

const PricingIndexRoute = PricingIndexImport.update({
	id: '/pricing/',
	path: '/pricing/',
	getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
	id: '/settings/',
	path: '/settings/',
	getParentRoute: () => rootRoute,
} as any)

const SettingsBillingIndexRoute = SettingsBillingIndexImport.update({
	id: '/settings/billing/',
	path: '/settings/billing/',
	getParentRoute: () => rootRoute,
} as any)

const SettingsProfileIndexRoute = SettingsProfileIndexImport.update({
	id: '/settings/profile/',
	path: '/settings/profile/',
	getParentRoute: () => rootRoute,
} as any)

const StudioCreateIndexRoute = StudioCreateIndexImport.update({
	id: '/studio/create/',
	path: '/studio/create/',
	getParentRoute: () => rootRoute,
} as any)

const StudioResultJobIdRoute = StudioResultJobIdImport.update({
	id: '/studio/result/$jobId',
	path: '/studio/result/$jobId',
	getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/dashboard/': {
			id: '/dashboard/'
			path: '/dashboard'
			fullPath: '/dashboard'
			preLoaderRoute: typeof DashboardIndexImport
			parentRoute: typeof rootRoute
		}
		'/login/': {
			id: '/login/'
			path: '/login'
			fullPath: '/login'
			preLoaderRoute: typeof LoginIndexImport
			parentRoute: typeof rootRoute
		}
		'/products/analyze/': {
			id: '/products/analyze/'
			path: '/products/analyze'
			fullPath: '/products/analyze'
			preLoaderRoute: typeof ProductsAnalyzeIndexImport
			parentRoute: typeof rootRoute
		}
		'/onboarding/': {
			id: '/onboarding/'
			path: '/onboarding'
			fullPath: '/onboarding'
			preLoaderRoute: typeof OnboardingIndexImport
			parentRoute: typeof rootRoute
		}
		'/pricing/': {
			id: '/pricing/'
			path: '/pricing'
			fullPath: '/pricing'
			preLoaderRoute: typeof PricingIndexImport
			parentRoute: typeof rootRoute
		}
		'/settings/': {
			id: '/settings/'
			path: '/settings'
			fullPath: '/settings'
			preLoaderRoute: typeof SettingsIndexImport
			parentRoute: typeof rootRoute
		}
		'/settings/billing/': {
			id: '/settings/billing/'
			path: '/settings/billing'
			fullPath: '/settings/billing'
			preLoaderRoute: typeof SettingsBillingIndexImport
			parentRoute: typeof rootRoute
		}
		'/settings/profile/': {
			id: '/settings/profile/'
			path: '/settings/profile'
			fullPath: '/settings/profile'
			preLoaderRoute: typeof SettingsProfileIndexImport
			parentRoute: typeof rootRoute
		}
		'/studio/create/': {
			id: '/studio/create/'
			path: '/studio/create'
			fullPath: '/studio/create'
			preLoaderRoute: typeof StudioCreateIndexImport
			parentRoute: typeof rootRoute
		}
		'/studio/result/$jobId': {
			id: '/studio/result/$jobId'
			path: '/studio/result/$jobId'
			fullPath: '/studio/result/$jobId'
			preLoaderRoute: typeof StudioResultJobIdImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
	DashboardIndexRoute,
	LoginIndexRoute,
	ProductsAnalyzeIndexRoute,
	OnboardingIndexRoute,
	PricingIndexRoute,
	SettingsIndexRoute,
	SettingsBillingIndexRoute,
	SettingsProfileIndexRoute,
	StudioCreateIndexRoute,
	StudioResultJobIdRoute,
})

/* prettier-ignore-end */
